const listDemands = [
  "Tecido/Sacaria",
  "Químicos/matéria-prima",
  "Papéis e máquinas",
  "Móveis e cosméticos",
  "Aço da China",
  "Açúcar",
  "Importação",
  "Artigos para embalagens",
  "Laser/Plasma",
  "Bags azuis de cosméticos",
  "Manga",
  "Peixes (pescado da amazonia)",
  "Akira + Andressa",
  "Lalef Chinesa (Latina)",
  "Relógios de xadrez",
  "QC inspection forklift Shandong",
  "Farinha de osso",
  "peças de máquinas injetoras diesel",
  "Bombas de água",
  "Contabilidade do 2000 USD pagos",
  "parceria importacao de pneus",
  "Interruptores",
  "Compressor e máquina a laser",
  "invoice de serviço ",
  "Laundry",
];

export default listDemands;
